// <auto-generated />
using System;
using ApiServer_Example.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiServer_Example.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ApiServer_Example.Domains.Models.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("ApiServer_Example.Domains.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiServer_Example.Domains.Models.User", b =>
                {
                    b.OwnsOne("ApiServer_Example.Domains.Models.RSAKeys", "RsaKeys", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<byte[]>("D")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("DP")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("DQ")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("Exponent")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("InverseQ")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("Modulus")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("P")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<byte[]>("Q")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
